CREATE TABLE CONTAS(
    ID SERIAL PRIMARY KEY,
    DESCRICAO VARCHAR(20),
    INATIVO BOOLEAN DEFAULT FALSE
);

CREATE TABLE CONTAS_PAGAR(
    ID SERIAL PRIMARY KEY,
    ID_CONTA INTEGER NOT NULL REFERENCES CONTAS(ID),
    PARCELA INTEGER NOT NULL,
    DATA_VENCIMENTO TIMESTAMP,
    VALOR NUMERIC(15,6),
    PAGO BOOLEAN DEFAULT FALSE
);

CREATE TABLE VEICULOS(
    ID SERIAL PRIMARY KEY,
    DESCRICAO VARCHAR(40)
);

CREATE TABLE CONTROLE_COMBUSTIVEIS(
    ID SERIAL PRIMARY KEY,
    ID_VEICULO INTEGER NOT NULL REFERENCES VEICULOS(ID),
    DATA_ABASTECIMENTO TIMESTAMP NOT NULL,
    ID_CONTA INTEGER NOT NULL REFERENCES CONTAS(ID),
    VALOR NUMERIC(15, 6)
);


